## Placeholder/documentation script for data for runnable examples. 

#' @title Synthetic TESSERA Example Data Files
#' @description The following files are stored in \code{inst/extdata} and are
#' used for runnable examples and unit tests within the TESSERA package.
#' @section Data Generation:
#' All datasets below were generated using the script located at:
#' \code{system.file("examples", "gen_data_and_run.R", package = "TESSERA")}
#' @name tessera_example_data
NULL

#' Raw Synthetic Spatial Data
#'
#' A list containing raw components for three simulated spatial areas,
#' including counts, coordinates, and adjacency matrices.
#'
#' @format A \code{.rds} file containing a list with 5 elements:
#' \describe{
#'   \item{count_matrix}{A 1x900 matrix of simulated counts.}
#'   \item{meta_data}{Data frame with sample identifiers.}
#'   \item{design_mat}{Design matrix for fixed effects.}
#'   \item{coords}{Matrix of spatial coordinates (x, y).}
#'   \item{W}{Block-diagonal sparse adjacency matrix.}
#' }
#' @name example_raw_data.rds
NULL

#' Pre-processed TESSERA Data Object
#'
#' An object of class \code{TESSERAData} (or the list format expected by
#' the package) generated by passing raw data through \code{prep_data()}.
#'
#' @format A \code{.rds} file containing the processed TESSERA data structure,
#' including filtered counts and spatial weights formatted for the Leroux model.
#' @name example_prepData.rds
NULL

#' Fitted TESSERA Leroux Model Object
#'
#' A fitted model object resulting from running \code{TESSERA_lattice}
#' on the example prepared data.
#'
#' @format A \code{.rds} file containing:
#' \describe{
#'   \item{beta_hat}{Estimated fixed effects.}
#'   \item{tau2_hat}{Estimated spatial variance.}
#'   \item{gamma_hat}{Estimated spatial correlation (Leroux parameter).}
#'   \item{...}{Other tracked quantities.}
#' }
#' @name example_TESSERA_out_Leroux.rds
NULL
