# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Helper function for Moran's I.
#'
#' @author Matthew Cooper.
#'
#' @param x1 First x-coordinate.
#' @param y1 First y-coordinate.
#' @param x2 Second x-coordinate.
#' @param y2 Second y-coordinate.
#'
#' @returns Euclidean distance between (x1, y1) and (x2, y2).
distanceCalculate <- function(x1, y1, x2, y2) {
    .Call('_TESSERA_distanceCalculate', PACKAGE = 'TESSERA', x1, y1, x2, y2)
}

#' Helper function for Moran's I: Center a vector.
#'
#' @author Matthew Cooper.
#'
#' @param x Measurements.
#'
#' @returns x - mean(x).
normalize <- function(x) {
    .Call('_TESSERA_normalize', PACKAGE = 'TESSERA', x)
}

#' Fast computation of Moran's I.
#'
#' @author Matthew Cooper.
#'
#' @param x Measurements.
#' @param c1 x-coordinates.
#' @param c2 y-coordinates.
#'
#' @returns I Moran's I.
#' @returns EI Expected value of Moran's I under the null of no
#'   spatial correlation.
#' @returns SD Standard deviation of Moran's I.
#'
#' @export
#' 
#' @examples
#' calc_moran(rpois(1000, 1), runif(1000), runif(1000))
calc_moran <- function(x, c1, c2) {
    .Call('_TESSERA_calc_moran', PACKAGE = 'TESSERA', x, c1, c2)
}

