# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distanceCalculate <- function(x1, y1, x2, y2) {
    .Call('_poisECM_distanceCalculate', PACKAGE = 'poisECM', x1, y1, x2, y2)
}

normalize <- function(x) {
    .Call('_poisECM_normalize', PACKAGE = 'poisECM', x)
}

calc_moran <- function(x, c1, c2) {
    .Call('_poisECM_calc_moran', PACKAGE = 'poisECM', x, c1, c2)
}

